version: '3.9'
services:
  python-dev:
    build: 
      context: .
      ssh:
        - default
    volumes:
      - ../..:/workspaces:cached
    privileged: true
    # network_mode: service:db
    command: sleep infinity

