[AppSetting]
ConfigFile="/workspaces/"
DBFile="/data/gopen.db"
SDHOST="python"
[ChatGPT]
ApiToken = ""
MaxTokens = 10
Model = "gpt-3.5-turbo"
Temperature=0.4
STEAM=true
BaseURL = "http://143.42.236.71:8443/v1"
