version: '3.9'
services:
  gopen:
    build: 
      context: .
      ssh:
        - default
      args:
        - GOPROXY=${GOPROXY}
    environment:
      - GO111MODULE=on
      - GOPROXY=${GOPROXY}
    volumes:
      - .:/workspaces/gopen:cached
      - data:/data
    privileged: true
    # command: sleep infinity
    ports:
      - "8080:8080"
    networks:
      - app_net

  proxy:
    image: nginx
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7211:7211"
    networks:
      - app_net
  
volumes:
  data:

networks:
  app_net: