version: '3.9'
services:
  goopen:
    build: 
      context: .
      ssh:
        - default
      args:
        - GOPROXY=${GOPROXY}
    environment:
      - GO111MODULE=on
      - GOPROXY=${GOPROXY}
    volumes:
      - .:/workspaces/gopen:cached
    privileged: true
    # command: sleep infinity
    ports:
      - "7211:8080"
    
  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres

# volumes:
#   postgres-data: