version: '3.9'
services:
  gopen:
    build: 
      context: ./golang
      ssh:
        - default
      args:
        - GOPROXY=${GOPROXY}
    environment:
      - GO111MODULE=on
      - GOPROXY=${GOPROXY}
    volumes:
      - ./golang:/workspaces/gopen:cached
      - data:/data
    privileged: true
    networks:
      - app_net
      
  gopen-init:
    build: 
      context: ./golang
      target: init
      ssh:
        - default
      args:
        - GOPROXY=${GOPROXY}
    environment:
      - GO111MODULE=on
      - GOPROXY=${GOPROXY}
    volumes:
      - data:/data
      - ./init/init.sh:/tmp/init.sh:ro
    # command: "sleep infinity"
    entrypoint: "/tmp/init.sh"
    privileged: true
    networks:
      - app_net


  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    ports:
      - 3000:3000
    environment:
      - UID=1000
      - GID=1000
    privileged: true
    volumes:
      - data:/app
    restart: unless-stopped
    networks:
      - app_net



  proxy:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7211:7211"
    networks:
      - app_net

  python:
    build: 
      context: ./python
    networks:
      - app_net
  
volumes:
  data:

networks:
  app_net: