version: '3.9'
services:
  devcontainer:
    environment: 
      - GOPROXY=https://goproxy.cn
      - TEST=123
    build: 
      context: .
      ssh:
        - default
    volumes:
      - ../..:/workspaces:cached
    privileged: true
    # network_mode: service:db
    command: sleep infinity

  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres

# volumes:
# #   postgres-data: