basePath: /api
definitions:
  api.App:
    properties:
      name:
        example: 商城商品
        type: string
      ord:
        type: integer
    type: object
  api.App_S:
    properties:
      attrs:
        items:
          $ref: '#/definitions/api.Attr'
        type: array
      name:
        type: string
    type: object
  api.Attr:
    properties:
      context:
        description: 内容
        example: 按照stable diffusion的关键字要求，给出主题鲜明的prompt,并使用英文文回答
        type: string
      context_type:
        description: 1 chat 2 edit
        example: 1
        type: integer
      id:
        description: Example ID
        example: 0
        type: integer
      name:
        description: Tab
        example: 商城商品
        type: string
      ord:
        example: 1
        type: integer
      sd_param:
        example: '{"width":512,"height":512}'
        type: string
      tips:
        example: 为了获得更优的反馈，请描述商品名称与商品特性，如'YSL/圣罗兰 416； 红黑管唇釉，易上色，湿润'
        type: string
      type:
        description: 1 chat completion 2 img
        enum:
        - 1
        - 2
        example: 1
        type: integer
    type: object
  api.ChatAttr:
    properties:
      context:
        items:
          $ref: '#/definitions/api.ChatCompletionMessage'
        type: array
      id:
        type: integer
      name:
        description: 属性名称
        example: 商城商品
        type: string
      ord:
        type: integer
      tips:
        example: 为了获得更优的反馈，请描述商品名称与商品特性，如'YSL/圣罗兰 416； 红黑管唇釉，易上色，湿润'
        type: string
      type:
        description: 1 纯文字 2 img
        example: 1
        type: integer
    type: object
  api.ChatCompletionMessage:
    properties:
      content:
        example: 请问今天是几号?
        type: string
      role:
        example: user
        type: string
    type: object
  api.ChatCompletionResponse:
    properties:
      context:
        type: string
    type: object
  api.SDParam:
    properties:
      height:
        type: integer
      negative_prompt:
        type: string
      prompt:
        type: string
      width:
        type: integer
    type: object
  api.TextToImgMessage:
    properties:
      sd_param:
        $ref: '#/definitions/api.SDParam'
      user_message:
        description: 用户输入
        type: string
    type: object
  api.UploadUrlResponse:
    properties:
      code:
        type: integer
      data:
        type: string
    type: object
  api.UserMessage:
    properties:
      content:
        type: string
    type: object
  common.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  common.SuccResponse:
    properties:
      succ:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a API documentation for OPENAI.
  title: OPENAI
  version: "1.0"
paths:
  /v1/apps:
    get:
      description: Get all apps
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.App'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get all apps
      tags:
      - App
    post:
      consumes:
      - application/json
      description: Creates a new app with the provided data
      parameters:
      - description: App data
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/api.App'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.App'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Create a new app
      tags:
      - App
  /v1/apps/{app_id}:
    delete:
      consumes:
      - application/json
      description: Delete an app by app ID
      parameters:
      - description: App ID
        in: path
        name: app_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted app
          schema:
            $ref: '#/definitions/common.SuccResponse'
        "400":
          description: Invalid app ID
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Delete an app
      tags:
      - App
  /v1/apps/{app_id}/attrs:
    get:
      description: Get all attrs
      parameters:
      - description: App ID
        in: path
        name: app_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Attr'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get  all Attrs by App ID
      tags:
      - Attr
    post:
      consumes:
      - application/json
      description: 用户通用属性创建 类型为chat请使用  CreateChatAttr
      parameters:
      - description: App ID
        in: path
        name: app_id
        required: true
        type: integer
      - description: Attr data
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/api.Attr'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Attr'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 通用Attr创建 (1 Chat 2 Edit )
      tags:
      - Attr
  /v1/apps/{app_id}/attrs/{attr_id}:
    get:
      description: Get Attr by ID
      parameters:
      - description: App ID
        in: path
        name: app_id
        required: true
        type: integer
      - description: Attr ID
        in: path
        name: attr_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Attr'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get Attr by ID
      tags:
      - Attr
  /v1/apps/{app_id}/chat_attrs:
    post:
      consumes:
      - application/json
      description: 使用提供的数据创建新的 对话Attr
      parameters:
      - description: 应用ID
        in: path
        name: app_id
        required: true
        type: integer
      - description: 更新的应用数据
        in: body
        name: appData
        required: true
        schema:
          $ref: '#/definitions/api.ChatAttr'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Attr'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 对话Attr创建
      tags:
      - Attr
  /v1/apps/{app_id}/chat_attrs/{attr_id}:
    put:
      consumes:
      - application/json
      description: 使用提供的数据创建新的 对话Attr
      parameters:
      - description: 应用ID
        in: path
        name: app_id
        required: true
        type: integer
      - description: AttrID
        in: path
        name: attr_id
        required: true
        type: integer
      - description: 更新的应用数据
        in: body
        name: appData
        required: true
        schema:
          $ref: '#/definitions/api.ChatAttr'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Attr'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 对话Attr更新
      tags:
      - Attr
  /v1/apps/{appID}/attrs/{attrID}:
    delete:
      consumes:
      - application/json
      description: Delete an attribute by providing the app ID, attribute ID, and
        updated attribute information
      parameters:
      - description: App ID
        format: int32
        in: path
        name: appID
        required: true
        type: integer
      - description: Attribute ID
        format: int32
        in: path
        name: attrID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/common.SuccResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Delete an attribute
      tags:
      - Attr
    put:
      consumes:
      - application/json
      description: Update an attribute by providing the app ID, attribute ID, and
        updated attribute information
      parameters:
      - description: App ID
        format: int32
        in: path
        name: appID
        required: true
        type: integer
      - description: Attribute ID
        format: int32
        in: path
        name: attrID
        required: true
        type: integer
      - description: Updated attribute information
        in: body
        name: updatedAttr
        required: true
        schema:
          $ref: '#/definitions/api.Attr'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/common.SuccResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Update an attribute
      tags:
      - Attr
  /v1/apps/{id}:
    get:
      description: Get app by ID
      parameters:
      - description: App ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.App_S'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get app by ID
      tags:
      - App
    put:
      consumes:
      - application/json
      description: 根据提供的应用ID和更新的应用数据更新应用信息
      parameters:
      - description: 应用ID
        in: path
        name: app_id
        required: true
        type: string
      - description: 更新的应用数据
        in: body
        name: appData
        required: true
        schema:
          $ref: '#/definitions/api.App'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.App'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 更新应用
      tags:
      - App
  /v1/apps/attrs:
    get:
      description: Get all attrs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Attr'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get all Attrs
      tags:
      - Attr
  /v1/gpt/{attrID}/chat-completion:
    post:
      consumes:
      - application/json
      description: Generate chat completion text based on input messages.
      parameters:
      - description: Attr ID
        in: path
        name: attrID
        required: true
        type: integer
      - description: User Messages
        in: body
        name: userMessage
        required: true
        schema:
          $ref: '#/definitions/api.UserMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ChatCompletionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Generate Chat Completion
      tags:
      - ChatGpt
  /v1/sd/{attr_id}/img2img:
    post:
      consumes:
      - multipart/form-data
      description: 将一张图片文件上传并转换成另一张图片
      parameters:
      - description: Attr ID
        in: path
        name: attr_id
        required: true
        type: integer
      - description: 待上传的图片文件
        in: formData
        name: image
        required: true
        type: file
      - description: 用户提交内容
        in: formData
        name: use_message
        required: true
        type: string
      - description: 生成图片宽度
        in: formData
        name: width
        type: integer
      - description: 生成图片高度
        in: formData
        name: height
        type: integer
      - description: prompt
        in: formData
        name: prompt
        type: string
      - description: negative_prompt
        in: formData
        name: negative_prompt
        type: string
      produces:
      - image/jpeg
      responses:
        "200":
          description: 图片文件
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 图片转换
      tags:
      - SD
  /v1/sd/{attr_id}/img2imgurl:
    post:
      consumes:
      - multipart/form-data
      description: 将一张图片文件上传并转换成另一张图片
      parameters:
      - description: Attr ID
        in: path
        name: attrID
        required: true
        type: integer
      - description: 待上传的图片文件
        in: formData
        name: image
        required: true
        type: file
      - description: 用户提交内容
        in: formData
        name: use_message
        required: true
        type: string
      - description: 生成图片宽度
        in: formData
        name: width
        type: integer
      - description: 生成图片高度
        in: formData
        name: height
        type: integer
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UploadUrlResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 图片转换
      tags:
      - SD
  /v1/sd/{attr_id}/txt2img:
    post:
      consumes:
      - application/json
      description: 将文本转换为图片
      parameters:
      - description: Attr ID
        format: int32
        in: path
        name: attr_id
        required: true
        type: integer
      - description: 更新的应用数据
        in: body
        name: appData
        required: true
        schema:
          $ref: '#/definitions/api.TextToImgMessage'
      produces:
      - image/jpeg
      responses:
        "200":
          description: 图片文件
          schema:
            type: file
        "500":
          description: 错误信息
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 文本转图片
      tags:
      - SD
  /v1/sd/{attr_id}/txt2imgurl:
    post:
      consumes:
      - application/json
      description: 将文本转换为图片
      parameters:
      - description: Attr ID
        format: int32
        in: path
        name: attr_id
        required: true
        type: integer
      - description: 更新的应用数据
        in: body
        name: appData
        required: true
        schema:
          $ref: '#/definitions/api.TextToImgMessage'
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UploadUrlResponse'
        "500":
          description: 错误信息
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: 文本转图片
      tags:
      - SD
swagger: "2.0"
